### PR TITLE
Create Click.py

### PR DESCRIPTION
**Pull request by Isometries**
This class will have to be called when it comes time to record all the click locations. It places them in a log file that also will be created. It should be called like this: 

`from Click import mouse_click
get_mouse_click = mouse_click('insert/path/here')`

If anybody has a better way to do it feel free to make changes.

### CODE REVIEW

**Comment by Isometries** [comment]
One problem that needs to be addressed is that the Linux version of `get_running_processes` returns a list of all the currently running proccesses and looks like: `['    2 ?        00:00:00 kthreadd', '    3 ?        00:00:00 ksoftirqd/0', '    7 ?        00:00:18 rcu_sched', '    8 ?        00:00:00 rcu_bh', '    9 ?        00:00:02 migration/0', '   10 ?        00:00:00 lru-add-drain']`.

It shouldn't be hard to do with `re`, but it's extra code in your function. The function needs to be changed back to `pids.append(line_)` since the `+=` doesn't work for me. The other problem is that you need to be able to handle the array called from `mouse_click.points`, which is an array such as `[(50,100),(459,504),...]`. 

If all that can be done, it _should_ work, but I'm probably missing something.

**Comment by Peter92** [comment]
Thanks, I guess if it's proving a bit difficult then `re` is fine. I dropped you the message about the mouse clicks anyway, if however it can't be done I could try write in a separate way of handling them in this format.

**Comment by Isometries** [comment]
I could probably add the `re` into the function itself, actually. If you give me an exact sample output for `get_running_processes` I should be able to make it work. 

I can't offer you any solutions for the mouse clicks. I had originally thought it was only needed to make the heat map, in which case an array of all clicked points would be perfectly fine. Maybe limiting the scope of the linux version is the best option for now. Get it working first and then maybe somebody more knowledgeable will come along and fix it. I think all that's left is cleaning import statements and organizing it all. I can try it out later this week on my debian testing desktop.

**Comment by Peter92** [comment]
[Here's](https://pastebin.com/hiCFH0iL) the result from mine. The ID roughly relates to the order that the programs were loaded, which I use to determine which game to track if multiple are running. It doesn't matter if you just assign some random numbers though, it's not very important as it won't happen often.

With the click function, I can try get it accepting lists of points, but it'd work perfectly with the current code if you could get it to return either `[0]` or `[1]` at the time it's called. I can't test it but I mean something a bit like [this](https://pastebin.com/xRVPu3gk). That way it'll still work with the values set in config.ini, such as repeating clicks if it's held down.

Also, I just had a quick look at `event` in `pyxhook` and found that you can use `event.Ascii == 32` to detect if the spacebar is being pressed. The mouse buttons are 1, 2 and 4 on windows, so have a quick check to see if `(event.Ascii == 1, event.Ascii == 4, event.Ascii == 2)` shows anything :)

**Comment by Isometries** [comment]
I tested your code and it works just fine with a minor adjustment. You should make the edit. https://pastebin.com/jX3GY4zB

I can make the pid function create a dictionary like yours, I'll try and get it done tomorrow if I have time. I'll let you know when I edit my pull request.

The `PyMouseEvent` class doesn't actually have an attribute for `Ascii`; it only works for keyboard events. You can see the source here: https://github.com/SavinaRoja/PyUserInput/blob/master/pymouse/x11.py

**Comment by Peter92** [comment]
Alright I made the edit, cheers for testing it out.
With `PyMouseEvent`, I'm not sure if it'd help or not, but the function `translate_button_code` seems to contain all 3 mouse buttons. Next time you load it up, it might be worth dropping `print translate_button_code(event.detail)` into the click function to see if it does anything :)

**Comment by Isometries** [comment]
I fixed the get_running_processes function. It was most easily done with rsplit() and not re. Is there anything else that needs to be done, or should I test it now?

**Comment by Peter92** [comment]
Nice one haha, and I haven't spotted anything about tracking keys, so either comment that part out or add a placeholder function that always returns `False`  and an empty `KEYS` dictionary, it might have crashed the background thread. You don't get a full traceback annoyingly as it's in a separate process, but it'll print out the error if you watch for it (set message level to 2 in messages.py to limit the less important parts), and a side effect is that it'll stop saving.

It's a bit of a pain to track down as the line number isn't accurate (I'll try tonight to see if I can get it working a little better), but I'll manually raise errors at certain points to try pinpoint where others are happening if I have a rough idea :P

**Comment by Isometries** [comment]
Just to be clear, the way you run this is by running `__init__.py` and then `generate_image.py`? I tried editing out the keys, and it still returns the same thing.

Also, how exactly does the `generate_image.py` script call the data? Where exactly are you storing it? Maybe the path isn't working for linux.

**Comment by Peter92** [comment]
`__init__.py` is everything to do with recording and saving (eg. "Alien Swarm: Reactive Drop" will be saved as `/Data/alienswarmreactivedrop.data`). `generate_images.py` is entirely separate and will load the file from the `Data` folder, so with default settings, you can only generate the first image after 120 seconds.

If it's not detecting anything from the file it's probably crashing somewhere before it can save. Set it to save every 10 seconds in the config, then it's more obvious if it crashes. Also double check permissions, it currently writes files to same path that the script is in.

**Comment by Isometries** [comment]
Yeah. something weird seems to be happening. If it's a permissions problem, the save location should be switched to desktop or something since giving root access should be avoided whenever possible. Any idea on what can be done? I fee like it's pretty much working since `__init__.py` works without errors.

**Comment by Peter92** [comment]
When you load `__init__.py` it also creates an entirely separate second process, so if that crashed, then the saving stops but it appears that the script is still running. I've actually fixed that now so it'll send the full traceback to the main process and stop the script, so I'd probably recommend just update the files if it's not too much of a pain, it's a lot easier to debug now :)

Good idea about the saving btw, I've got a config option for the save path so the ability to change location is there (I'd forgotten to test until now), using `%APPDATA%` doesn't do anything though so I'll have to look at getting the OS specific paths to use for a default location.

**Comment by Isometries** [comment]
I tried working with the new build and was getting a lot of KeyErrors. I fixed some of it by using the code from the first version, but then I had problems when calling `generate_images.py`. 

```
  File "/home/user/Desktop/MouseTrack_new/core/image.py", line 367, in generate
    value_range, numpy_arrays = merge_resolutions(self.data['Maps']['Tracks'])
KeyError: 'Maps'
```

**Comment by Peter92** [comment]
First error will probably be because the file doesn't exist yet, I recently changed where the tracks are stored so it's just lacking the error check.

That's really weird with the saving though unless it's specific to linux, I just installed python 3 to test it out and have managed to get it working fine on my PC, [here](https://1drv.ms/u/s!Ai6sg-RxOdJhngTOdcnxB9tpv1xS) are the files with a few minutes of tracks. I don't have all the modules on 3 though, so I'm unsure if generating images properly works.

**Comment by Isometries** [comment]
It all works except for the heatmap! This is the traceback: 

```
Traceback (most recent call last):
  File "generate_images.py", line 8, in <module>
    r.generate('Clicks')
  File "/home/user/Desktop/MouseTrack2/core/image.py", line 384, in generate
    image_output = _click_heatmap(numpy_arrays)
  File "/home/user/Desktop/MouseTrack2/core/image.py", line 337, in _click_heatmap
    colour_range = ColourRange(min_value, max_value, ColourMap()[colour_map])
  File "/home/user/Desktop/MouseTrack2/core/image.py", line 429, in __getitem__
    raise ValueError('not enough values input')
ValueError: not enough values input
```

**Comment by Peter92** [comment]
That's the error that appears when it's working with less than 2 colours, I've just changed it as it's not too obvious haha. In `config.ini` under `[GenerateHeatmap]`, set `ColourProfile` to either `Jet` or `Radiation`. I accidentally left it as heatmap which no longer exists :)

**Comment by Isometries** [comment]
There was a little typo in one of the files.

So it looks like it's all working, I just tried it out, glad it finally got merged. There is still one tiny problem though. The class `pyxhook` has to be taken from the source over at: https://github.com/JeffHoogland/pyxhook

I've actually just been throwing it in the directory `MouseTrack/core/os/linux`, and if we are able to, I think it's easier if we include it in the repo here. I'm not actually sure how it works with licensing though.

**Comment by Peter92** [comment]
Thanks for spotting it haha. I had a quick look over at pyxhook and the license says people are free to redistribute, so that's pretty decent. I'll add it in and update the imports :)

**Comment by Isometries** [comment]
It's working smoothly now. No problems with the quick test I just did. I'll fiddle with making a `get_keys` type function. It shouldn't be that hard. That will probably be the last thing this needs to be complete. 

In the readme you should just note that this  will only run with X11. If you're running fedora25 on a fresh install it just won't work unless you switch from wayland.

**Comment by Peter92** [comment]
Thanks for all the effort haha. I'm just wondering what part actually needs python 3?

As to the linux versions, is it only `xlib` that won't work with other versions? I had a quick look to see if `platform` could detect it, but for some reason all the functions relating to linux versions are getting depreciated, so I came across [this](http://stackoverflow.com/a/19694625/2403000) answer instead. It'd probably be better adding in a version check if possible instead of just failing to import :)

**Pull request merged**
